### ISSUE TITLE
How do I get the ID of the Select?

### ISSUE THREAD

**Issue by autumnleafsoftware** [koenpunt/chosen#14]
I am using the chosen plugin for jQuery and love it but I am trying to create a common script to use for all SELECT within my application that have a certain class. The problem is I am trying to get the ID for the active Chosen Select. Below is my JavaScript jQuery code.

<pre>
$("SELECT.editable").chosen({        
        create_option: function (term) {
            var chosen = this;
            chosen.append_option({
                value: term,
                text: term
            });
            var tableField = $(this).attr('id');   ////////  HERE IS THE ISSUE. I am trying to get the ID of the select to pass to the jQuery post as a paramter. It comes back as undefined.
            alert(tableField);
            var params = { optionValue: term, tableField: tableField };
            var paramsStr = $.param(params);
            var actionUrl = '/Setup/_addDropDownOption';
            $.post(actionUrl, paramsStr);
        },
        persistent_create_option: false,
        create_option_text: 'Add Option',
        allow_single_deselect: true
    });
</pre>

I have tried the following with no success.

$(this).attr('id');
this.id;
chosen.id;
variations of $().parent() and $().sibilings() and $().closest()

nothing above seems to return the ID of the SELECT.

Thanks,
Shawn

**Comment by koenpunt** [comment]
For inspecting javascript objects in the browser you could use the developer console (Chrome, Safari, and as Firebug for Firefox), and when placing the following in the `create_option` function instead of your `alert(this)`: 

``` javascript
console.log(this);
```

It shows you that the property `form_field` (`this.form_field`) is a reference to the original select, so using the following will return the correct id:

``` javascript
$(this.form_field).attr('id');
```

Update: 
FYI: `this` in the function is the `Chosen` object

**Comment by autumnleafsoftware** [comment]
Thanks, it worked like a charm.
